#!/bin/sh -e
# Copyright (c) 2014 The crouton Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# This file is sourced from main.sh to update distro-specific defaults.
# It must set at least ARCH and MIRROR if not already specified.

if [ -z "$ARCH" ]; then
    ARCH="`uname -m`"
fi

case "$ARCH" in
x86 | i?86) ARCH="i686";;
x86_64 | amd64) ARCH="x86_64";;
arm*) ARCH="armv7h";;
*) error 2 "Invalid architecture '$ARCH'.";;
esac

if [ -z "$MIRROR" ]; then
    case "$ARCH" in
    i686 ) MIRROR="${CROUTON_MIRROR_arch:-https://mirror.archlinux32.org/\$arch/\$repo}";;
    x86_64 ) MIRROR="${CROUTON_MIRROR_arch:-https://mirrors.kernel.org/archlinux/\$repo/os/\$arch}";;
    armv7h ) MIRROR="${CROUTON_MIRROR_alarm:-http://mirror.archlinuxarm.org/armv7h/\$repo}";;
    esac
fi
